
export default {
  NUMBER_ITEMS_PER_PAGE: 20,
  NUMBER_CHART_COLUMNS: 6,
  MAX_LENGTH_CHART_LABEL: 18,
  NUMBER_OF_ORDER_LENGTH: 5,
  MIN_LENGTH_SEARCH: 2,
  CLOSE_INTERVAL_ALERT_ERROR: 1000,
  CLOSE_INTERVAL_ALERT_SUCCESS: 500,
  VAT: 0.1, //10%,
};
